export const columnTitles = [
  'Athlete',
  'Started',
  'Min',
  'T',
  'T Att 3rd',
  'FA',
  'TO',
  'SH',
  'CK',
  'FK',
  'GK',
  'GTh',
  'P',
  'W',
  'W%',
];

export const columns = [
  {
    title: 'Passing',
    children: [
      {
        title: 'Athlete',
        dataIndex: 'Athlete',
        key: 'Athlete',
        width: 60,
        sorter: (a, b) => a.Athlete - b.Athlete,
      },
      {
        title: 'Started',
        dataIndex: 'Started',
        key: 'Started',
        width: 60,
        sorter: (a, b) => a.Started.length - b.Started.length,
      },
      {
        title: 'Min',
        dataIndex: 'Min',
        key: 'Min',
        width: 60,
        sorter: (a, b) => a.Min - b.Min,
      },
      {
        title: 'T',
        dataIndex: 'T',
        key: 'T',
        width: 60,
        sorter: (a, b) => a.T - b.T,
      },
      {
        title: 'T Att 3rd',
        dataIndex: 'T Att 3rd',
        key: 'T Att 3rd',
        width: 60,
      },
      {
        title: 'FA',
        dataIndex: 'FA',
        key: 'FA',
        width: 60,
        sorter: (a, b) => a.FA - b.FA,
      },
      {
        title: 'TO',
        dataIndex: 'TO',
        key: 'TO',
        width: 60,
        sorter: (a, b) => a.TO - b.TO,
      },
      {
        title: 'SH',
        dataIndex: 'SH',
        key: 'SH',
        width: 60,
        sorter: (a, b) => a.SH - b.SH,
      },
      {
        title: 'CK',
        dataIndex: 'CK',
        key: 'CK',
        width: 60,
        sorter: (a, b) => a.CK - b.CK,
      },
      {
        title: 'FK',
        dataIndex: 'FK',
        key: 'FK',
        width: 60,
        sorter: (a, b) => a.FK - b.FK,
      },
      {
        title: 'Cr',
        dataIndex: 'Cr',
        key: 'Cr',
        width: 60,
        sorter: (a, b) => a.Cr - b.Cr,
      },
      {
        title: 'TI',
        dataIndex: 'TI',
        key: 'TI',
        width: 60,
        sorter: (a, b) => a.TI - b.TI,
      },
      {
        title: 'GK',
        dataIndex: 'GK',
        key: 'GK',
        width: 100,
        sorter: (a, b) => a.GK - b.GK,
      },
      {
        title: 'GTh',
        dataIndex: 'GTh',
        key: 'GTh',
        width: 100,
        sorter: (a, b) => a.GTh - b.GTh,
      },
      {
        title: 'P',
        dataIndex: 'P',
        key: 'P',
        width: 100,
        sorter: (a, b) => a.P - b.P,
      },
      {
        title: 'W',
        dataIndex: 'W',
        key: 'W',
        width: 100,
        sorter: (a, b) => a.W - b.W,
      },
    ],
  },
  {
    title: 'touches',
    children: [
      {
        title: 'W%',
        dataIndex: 'W%',
        key: 'W%',
        width: 100,
      },
      {
        title: 'Total',
        dataIndex: 'Total',
        key: 'Total',
        width: 100,
        sorter: (a, b) => a.Total - b.Total,
      },
      {
        title: 'Att',
        dataIndex: 'Att',
        key: 'Att',
        width: 60,
        sorter: (a, b) => a.Att - b.Att,
      },
      {
        title: 'Mid',
        dataIndex: 'Mid',
        key: 'Mid',
        width: 60,
        sorter: (a, b) => a.Mid - b.Mid,
      },
      {
        title: 'Def',
        dataIndex: 'Def',
        key: 'Def',
        width: 100,
        sorter: (a, b) => a.Def - b.Def,
      },
      {
        title: 'Fwd',
        dataIndex: 'Fwd',
        key: 'Fwd',
        width: 100,
        sorter: (a, b) => a.Fwd - b.Fwd,
      },
      {
        title: 'Fwd Att 3rd',
        dataIndex: 'Fwd Att 3rd',
        key: 'Fwd Att 3rd',
        width: 100,
      },
      {
        title: 'Bck',
        dataIndex: 'Bck',
        key: 'Bck',
        width: 100,
        sorter: (a, b) => a.Bck - b.Bck,
      },
      {
        title: 'Sde',
        dataIndex: 'Sde',
        key: 'Sde',
        width: 100,
        sorter: (a, b) => a.Sde - b.Sde,
      },
      {
        title: 'Sh',
        dataIndex: 'Sh',
        key: 'Sh',
        width: 100,
        sorter: (a, b) => a.Sh - b.Sh,
      },
      {
        title: 'Med',
        dataIndex: 'Med',
        key: 'Med',
        width: 100,
        sorter: (a, b) => a.Med - b.Med,
      },
      {
        title: 'Lng',
        dataIndex: 'Lng',
        key: 'Lng',
        width: 100,
        sorter: (a, b) => a.Lng - b.Lng,
      },
    ],
  },
];
